version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=bessma_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    networks:
      - bessma-network
    command: ["/bin/bash", "/var/www/html/docker-entrypoint.sh"]

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=bessma_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - bessma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bessma_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bessma-network:
    driver: bridge

volumes:
  postgres_data: